(cl:defpackage ros_topics_services-srv
  (:use )
  (:export
   "ADDTWOINTS"
   "<ADDTWOINTS-REQUEST>"
   "ADDTWOINTS-REQUEST"
   "<ADDTWOINTS-RESPONSE>"
   "ADDTWOINTS-RESPONSE"
   "RECTANGLEAREA"
   "<RECTANGLEAREA-REQUEST>"
   "RECTANGLEAREA-REQUEST"
   "<RECTANGLEAREA-RESPONSE>"
   "RECTANGLEAREA-RESPONSE"
  ))

