// Generated by gencpp from file ros_topics_services/add_two_ints.msg
// DO NOT EDIT!


#ifndef ROS_TOPICS_SERVICES_MESSAGE_ADD_TWO_INTS_H
#define ROS_TOPICS_SERVICES_MESSAGE_ADD_TWO_INTS_H

#include <ros/service_traits.h>


#include <ros_topics_services/add_two_intsRequest.h>
#include <ros_topics_services/add_two_intsResponse.h>


namespace ros_topics_services
{

struct add_two_ints
{

typedef add_two_intsRequest Request;
typedef add_two_intsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct add_two_ints
} // namespace ros_topics_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_topics_services::add_two_ints > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::ros_topics_services::add_two_ints&) { return value(); }
};

template<>
struct DataType< ::ros_topics_services::add_two_ints > {
  static const char* value()
  {
    return "ros_topics_services/add_two_ints";
  }

  static const char* value(const ::ros_topics_services::add_two_ints&) { return value(); }
};


// service_traits::MD5Sum< ::ros_topics_services::add_two_intsRequest> should match
// service_traits::MD5Sum< ::ros_topics_services::add_two_ints >
template<>
struct MD5Sum< ::ros_topics_services::add_two_intsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_topics_services::add_two_ints >::value();
  }
  static const char* value(const ::ros_topics_services::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_topics_services::add_two_intsRequest> should match
// service_traits::DataType< ::ros_topics_services::add_two_ints >
template<>
struct DataType< ::ros_topics_services::add_two_intsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_topics_services::add_two_ints >::value();
  }
  static const char* value(const ::ros_topics_services::add_two_intsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_topics_services::add_two_intsResponse> should match
// service_traits::MD5Sum< ::ros_topics_services::add_two_ints >
template<>
struct MD5Sum< ::ros_topics_services::add_two_intsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_topics_services::add_two_ints >::value();
  }
  static const char* value(const ::ros_topics_services::add_two_intsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_topics_services::add_two_intsResponse> should match
// service_traits::DataType< ::ros_topics_services::add_two_ints >
template<>
struct DataType< ::ros_topics_services::add_two_intsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_topics_services::add_two_ints >::value();
  }
  static const char* value(const ::ros_topics_services::add_two_intsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TOPICS_SERVICES_MESSAGE_ADD_TWO_INTS_H
