// Generated by gencpp from file ros_topics_services/AddTwoInts.msg
// DO NOT EDIT!


#ifndef ROS_TOPICS_SERVICES_MESSAGE_ADDTWOINTS_H
#define ROS_TOPICS_SERVICES_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <ros_topics_services/AddTwoIntsRequest.h>
#include <ros_topics_services/AddTwoIntsResponse.h>


namespace ros_topics_services
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace ros_topics_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_topics_services::AddTwoInts > {
  static const char* value()
  {
    return "f0b6d69ea10b0cf210cb349d58d59e8f";
  }

  static const char* value(const ::ros_topics_services::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::ros_topics_services::AddTwoInts > {
  static const char* value()
  {
    return "ros_topics_services/AddTwoInts";
  }

  static const char* value(const ::ros_topics_services::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::ros_topics_services::AddTwoIntsRequest> should match
// service_traits::MD5Sum< ::ros_topics_services::AddTwoInts >
template<>
struct MD5Sum< ::ros_topics_services::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_topics_services::AddTwoInts >::value();
  }
  static const char* value(const ::ros_topics_services::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_topics_services::AddTwoIntsRequest> should match
// service_traits::DataType< ::ros_topics_services::AddTwoInts >
template<>
struct DataType< ::ros_topics_services::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::ros_topics_services::AddTwoInts >::value();
  }
  static const char* value(const ::ros_topics_services::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_topics_services::AddTwoIntsResponse> should match
// service_traits::MD5Sum< ::ros_topics_services::AddTwoInts >
template<>
struct MD5Sum< ::ros_topics_services::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_topics_services::AddTwoInts >::value();
  }
  static const char* value(const ::ros_topics_services::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_topics_services::AddTwoIntsResponse> should match
// service_traits::DataType< ::ros_topics_services::AddTwoInts >
template<>
struct DataType< ::ros_topics_services::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::ros_topics_services::AddTwoInts >::value();
  }
  static const char* value(const ::ros_topics_services::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TOPICS_SERVICES_MESSAGE_ADDTWOINTS_H
