// Generated by gencpp from file ros_topics_services/Bio.msg
// DO NOT EDIT!


#ifndef ROS_TOPICS_SERVICES_MESSAGE_BIO_H
#define ROS_TOPICS_SERVICES_MESSAGE_BIO_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_topics_services
{
template <class ContainerAllocator>
struct Bio_
{
  typedef Bio_<ContainerAllocator> Type;

  Bio_()
    : name()
    , age(0)
    , height(0.0)
    , weight(0.0)
    , goal()  {
    }
  Bio_(const ContainerAllocator& _alloc)
    : name(_alloc)
    , age(0)
    , height(0.0)
    , weight(0.0)
    , goal(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _name_type;
  _name_type name;

   typedef int32_t _age_type;
  _age_type age;

   typedef float _height_type;
  _height_type height;

   typedef float _weight_type;
  _weight_type weight;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _goal_type;
  _goal_type goal;





  typedef boost::shared_ptr< ::ros_topics_services::Bio_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_topics_services::Bio_<ContainerAllocator> const> ConstPtr;

}; // struct Bio_

typedef ::ros_topics_services::Bio_<std::allocator<void> > Bio;

typedef boost::shared_ptr< ::ros_topics_services::Bio > BioPtr;
typedef boost::shared_ptr< ::ros_topics_services::Bio const> BioConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_topics_services::Bio_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_topics_services::Bio_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_topics_services::Bio_<ContainerAllocator1> & lhs, const ::ros_topics_services::Bio_<ContainerAllocator2> & rhs)
{
  return lhs.name == rhs.name &&
    lhs.age == rhs.age &&
    lhs.height == rhs.height &&
    lhs.weight == rhs.weight &&
    lhs.goal == rhs.goal;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_topics_services::Bio_<ContainerAllocator1> & lhs, const ::ros_topics_services::Bio_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_topics_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_topics_services::Bio_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_topics_services::Bio_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_topics_services::Bio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_topics_services::Bio_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_topics_services::Bio_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_topics_services::Bio_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_topics_services::Bio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2f30f91b8986a298de0f6ddc671bda5b";
  }

  static const char* value(const ::ros_topics_services::Bio_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2f30f91b8986a298ULL;
  static const uint64_t static_value2 = 0xde0f6ddc671bda5bULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_topics_services::Bio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_topics_services/Bio";
  }

  static const char* value(const ::ros_topics_services::Bio_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_topics_services::Bio_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string name\n"
"int32 age\n"
"float32 height\n"
"float32 weight\n"
"string goal\n"
;
  }

  static const char* value(const ::ros_topics_services::Bio_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_topics_services::Bio_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.name);
      stream.next(m.age);
      stream.next(m.height);
      stream.next(m.weight);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Bio_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_topics_services::Bio_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_topics_services::Bio_<ContainerAllocator>& v)
  {
    s << indent << "name: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.name);
    s << indent << "age: ";
    Printer<int32_t>::stream(s, indent + "  ", v.age);
    s << indent << "height: ";
    Printer<float>::stream(s, indent + "  ", v.height);
    s << indent << "weight: ";
    Printer<float>::stream(s, indent + "  ", v.weight);
    s << indent << "goal: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TOPICS_SERVICES_MESSAGE_BIO_H
