// Generated by gencpp from file ros_topics_services/RectangleAreaRequest.msg
// DO NOT EDIT!


#ifndef ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREAREQUEST_H
#define ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREAREQUEST_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_topics_services
{
template <class ContainerAllocator>
struct RectangleAreaRequest_
{
  typedef RectangleAreaRequest_<ContainerAllocator> Type;

  RectangleAreaRequest_()
    : height(0)
    , length(0)  {
    }
  RectangleAreaRequest_(const ContainerAllocator& _alloc)
    : height(0)
    , length(0)  {
  (void)_alloc;
    }



   typedef int32_t _height_type;
  _height_type height;

   typedef int32_t _length_type;
  _length_type length;





  typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleAreaRequest_

typedef ::ros_topics_services::RectangleAreaRequest_<std::allocator<void> > RectangleAreaRequest;

typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaRequest > RectangleAreaRequestPtr;
typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaRequest const> RectangleAreaRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator1> & lhs, const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator2> & rhs)
{
  return lhs.height == rhs.height &&
    lhs.length == rhs.length;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator1> & lhs, const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_topics_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4da6f69ccbb1d979d2e3ecadd3a8a41c";
  }

  static const char* value(const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4da6f69ccbb1d979ULL;
  static const uint64_t static_value2 = 0xd2e3ecadd3a8a41cULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_topics_services/RectangleAreaRequest";
  }

  static const char* value(const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#input \n"
"int32 height\n"
"int32 length\n"
;
  }

  static const char* value(const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.height);
      stream.next(m.length);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleAreaRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_topics_services::RectangleAreaRequest_<ContainerAllocator>& v)
  {
    s << indent << "height: ";
    Printer<int32_t>::stream(s, indent + "  ", v.height);
    s << indent << "length: ";
    Printer<int32_t>::stream(s, indent + "  ", v.length);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREAREQUEST_H
