// Generated by gencpp from file ros_topics_services/RectangleArea.msg
// DO NOT EDIT!


#ifndef ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREA_H
#define ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREA_H

#include <ros/service_traits.h>


#include <ros_topics_services/RectangleAreaRequest.h>
#include <ros_topics_services/RectangleAreaResponse.h>


namespace ros_topics_services
{

struct RectangleArea
{

typedef RectangleAreaRequest Request;
typedef RectangleAreaResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RectangleArea
} // namespace ros_topics_services


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ros_topics_services::RectangleArea > {
  static const char* value()
  {
    return "6b0cfd5befd2de410547c4b17bd912bb";
  }

  static const char* value(const ::ros_topics_services::RectangleArea&) { return value(); }
};

template<>
struct DataType< ::ros_topics_services::RectangleArea > {
  static const char* value()
  {
    return "ros_topics_services/RectangleArea";
  }

  static const char* value(const ::ros_topics_services::RectangleArea&) { return value(); }
};


// service_traits::MD5Sum< ::ros_topics_services::RectangleAreaRequest> should match
// service_traits::MD5Sum< ::ros_topics_services::RectangleArea >
template<>
struct MD5Sum< ::ros_topics_services::RectangleAreaRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ros_topics_services::RectangleArea >::value();
  }
  static const char* value(const ::ros_topics_services::RectangleAreaRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_topics_services::RectangleAreaRequest> should match
// service_traits::DataType< ::ros_topics_services::RectangleArea >
template<>
struct DataType< ::ros_topics_services::RectangleAreaRequest>
{
  static const char* value()
  {
    return DataType< ::ros_topics_services::RectangleArea >::value();
  }
  static const char* value(const ::ros_topics_services::RectangleAreaRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ros_topics_services::RectangleAreaResponse> should match
// service_traits::MD5Sum< ::ros_topics_services::RectangleArea >
template<>
struct MD5Sum< ::ros_topics_services::RectangleAreaResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ros_topics_services::RectangleArea >::value();
  }
  static const char* value(const ::ros_topics_services::RectangleAreaResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ros_topics_services::RectangleAreaResponse> should match
// service_traits::DataType< ::ros_topics_services::RectangleArea >
template<>
struct DataType< ::ros_topics_services::RectangleAreaResponse>
{
  static const char* value()
  {
    return DataType< ::ros_topics_services::RectangleArea >::value();
  }
  static const char* value(const ::ros_topics_services::RectangleAreaResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREA_H
