// Generated by gencpp from file ros_topics_services/RectangleAreaResponse.msg
// DO NOT EDIT!


#ifndef ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREARESPONSE_H
#define ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREARESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ros_topics_services
{
template <class ContainerAllocator>
struct RectangleAreaResponse_
{
  typedef RectangleAreaResponse_<ContainerAllocator> Type;

  RectangleAreaResponse_()
    : area(0)  {
    }
  RectangleAreaResponse_(const ContainerAllocator& _alloc)
    : area(0)  {
  (void)_alloc;
    }



   typedef int32_t _area_type;
  _area_type area;





  typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> const> ConstPtr;

}; // struct RectangleAreaResponse_

typedef ::ros_topics_services::RectangleAreaResponse_<std::allocator<void> > RectangleAreaResponse;

typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaResponse > RectangleAreaResponsePtr;
typedef boost::shared_ptr< ::ros_topics_services::RectangleAreaResponse const> RectangleAreaResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator1> & lhs, const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator2> & rhs)
{
  return lhs.area == rhs.area;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator1> & lhs, const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ros_topics_services

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6f6af7c0004b76d2160e3d1abb2fbee2";
  }

  static const char* value(const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6f6af7c0004b76d2ULL;
  static const uint64_t static_value2 = 0x160e3d1abb2fbee2ULL;
};

template<class ContainerAllocator>
struct DataType< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ros_topics_services/RectangleAreaResponse";
  }

  static const char* value(const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "#output\n"
"int32 area\n"
;
  }

  static const char* value(const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.area);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectangleAreaResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ros_topics_services::RectangleAreaResponse_<ContainerAllocator>& v)
  {
    s << indent << "area: ";
    Printer<int32_t>::stream(s, indent + "  ", v.area);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROS_TOPICS_SERVICES_MESSAGE_RECTANGLEAREARESPONSE_H
